apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-dns
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/hacwa/cloudflare
    targetRevision: HEAD
    path: argo/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
