apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-dns
  namespace: argo
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: default
      containers:
        - name: terraform
          image: hashicorp/terraform:light
          command: [sh, -c]
          args:
            - |
              apk add --no-cache git bash curl jq openssh &&
              git config --global credential.helper "" &&
              git clone https://github.com/hacwa/cloudflare /workspace &&
              cd /workspace/terraform &&
              terraform init &&
              terraform apply -auto-approve
          env:
            - name: TF_VAR_cloudflare_api_token
              valueFrom:
                secretKeyRef:
                  name: terraform-creds
                  key: CLOUDFLARE_API_TOKEN
            - name: TF_VAR_cloudflare_zone_id
              valueFrom:
                secretKeyRef:
                  name: terraform-creds
                  key: CLOUDFLARE_ZONE_ID
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: terraform-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: terraform-creds
                  key: AWS_SECRET_ACCESS_KEY
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir: {}
